export { roles } from "./collections/roles"
export { departmentPeople } from "./collections/departmentPeople"
export { newsCategories } from "./collections/newsCategories"
export { news } from "./collections/news"
export { announcements } from "./collections/announcements"
export { global } from "./collections/global"
export { pages } from "./collections/pages"
export { vacancies } from "./collections/vacancies"
